[versions]
guava = "33.2.1-jre"
logback = "1.5.6"

assertj = "3.26.3"
jupiter = "5.10.3"

shadow = "8.1.1"


[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }


[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj"}
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter"}
