[versions]
assertj = "3.26.3"
guava = "33.2.1-jre"
jupiter = "5.10.3"

shadow = "8.1.1"


[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }


[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj"}
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter"}
